apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database
  template:
    metadata:
      labels:
        name: database
    spec:
      containers:
      - name: database
        image: postgres:13.1
        envFrom:
        - configMapRef:
            name: postgres-config
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    name: database
  ports:
  - port: 5432
    targetPort: 5432
